services:
  postgres:
    env_file:
      - ./env/backend.dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: development
    env_file:
      - ./env/backend.dev.env
    ports:
      - "3000:3000"
    volumes:
      - ./shared_assets:/app/assets
    networks:
      - app-network

  data_management:
    build:
      context: ./data_management
      target: development
    env_file:
      - ./env/datamanagement.dev.env
    volumes:
      - ./shared_assets:/app/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: development
    env_file:
      - ./env/frontend.dev.env
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: parliament_visualiser_app-network
