services:
  postgres:
    env_file: .env.dev
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: development
    env_file: .env.dev
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./shared_assets:/app/assets
    networks:
      - app-network

  data_management:
    build:
      context: ./data_management
      target: development
    env_file: .env.dev
    volumes:
      - ./shared_assets:/app/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: development
    env_file: .env.dev
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: parliament_visualiser_app-network
