services:
  postgres:
    env_file:
      - ./backend/.env.prod
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: production
    env_file:
      - ./backend/.env.prod
    ports:
      - "3000:3000"
    volumes:
      - ./shared_assets:/app/assets
    networks:
      - app-network

  data_management:
    build:
      context: ./data_management
      target: production
    env_file:
      - ./data_management/.env.prod
    volumes:
      - ./shared_assets:/app/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_BACKEND_API_URL: "${VITE_BACKEND_API_URL}"
    env_file:
      - ./frontend/.env.prod
    ports:
      - "3001:3001"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: parliament_visualiser_app-network
