services:
  postgres:
    env_file: .env.prod
    expose:
      - "${DB_PORT:-5432}"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: production
    env_file: .env.prod
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network

  data_management:
    build:
      context: ./data_management
      target: production
    env_file: .env.prod
    networks:
      - app-network

  remix-app:
    build:
      context: ./remix-app
      target: production
      args:
        VITE_BACKEND_API_URL: "https://mysite.com"
    env_file: .env.prod
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - remix-app
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: parliament_visualiser_app-network
